spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/db_exam?useSSL=false&serverTimezone=UTC
    username: root
    password: 
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081
  
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level ${PID:- } [%thread] %logger{36} - %msg%n"

joblogger:
  logToFile: true
  logToConsole: true
  logToDatabase: true
  logMessage: true
  logWarning: true
  logError: true
  
    
    